language: go

cache:
  directories:
    - $HOME/.cache/go-build
    - $HOME/gopath/pkg/mod

env:
  - GO111MODULE=on

go:
  - "1.11"
  - "1.12"

install:
  - curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s -- -b $(go env GOPATH)/bin v1.16.0
  - go get -u github.com/modocache/gover
  - go get

script:
  - golangci-lint run shodan
  - go test -race -coverprofile=coverage.txt -covermode=atomic ./shodan/

after_success:
  - bash <(curl -s https://codecov.io/bash) -f ./coverage.txt
