language: go

cache:
  directories:
    - $HOME/.cache/go-build
    - $HOME/gopath/pkg/mod

env:
  - GO111MODULE=on

go:
  - "1.11"
  - "1.12"

install:
  - go get -u github.com/modocache/gover
  - go get -u golang.org/x/lint/golint
  - go get -u github.com/gordonklaus/ineffassign
  - go get -u github.com/client9/misspell/cmd/misspell
  - go get

script:
  - golint -set_exit_status ./shodan/...
  - ineffassign ./shodan/
  - misspell -error README.md ./shodan/**/*
  - gofmt -l shodan/ | read && echo "Code differs from gofmt's style" 1>&2 && exit 1 || true
  - go test -race -coverprofile=coverage.txt -covermode=atomic ./shodan/

after_success:
  - bash <(curl -s https://codecov.io/bash) -f ./coverage.txt
